<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.apimix</groupId>
        <artifactId>ApiMix</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>apimix-api</artifactId>
    <description>
        API 模块
    </description>

    <dependencies>

        <!-- 公共模块 -->
        <dependency>
            <groupId>cn.apimix</groupId>
            <artifactId>apimix-common</artifactId>
        </dependency>

        <!-- 核心模块 -->
        <dependency>
            <groupId>cn.apimix</groupId>
            <artifactId>apimix-core</artifactId>
        </dependency>

        <!-- 实体模块 -->
        <dependency>
            <groupId>cn.apimix</groupId>
            <artifactId>apimix-module-model</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <!-- 服务模块 -->
        <dependency>
            <groupId>cn.apimix</groupId>
            <artifactId>apimix-module-admin</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <!-- 评论模块 -->
        <dependency>
            <groupId>cn.apimix</groupId>
            <artifactId>apimix-module-comment</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <!-- 审核模块 -->
        <dependency>
            <groupId>cn.apimix</groupId>
            <artifactId>apimix-module-audit</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>cn.apimix</groupId>
            <artifactId>apimix-module-user</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>


        <dependency>
            <groupId>cn.apimix</groupId>
            <artifactId>apimix-module-api</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>


        <!-- AOP 切面 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>


        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!--dubbo相关-->
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>${dubbo.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.xkcoding.justauth</groupId>
            <artifactId>justauth-spring-boot-starter</artifactId>
        </dependency>



        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <version>${dubbo.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.dubbo</groupId>
                    <artifactId>dubbo-common</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.dubbo</groupId>
                    <artifactId>dubbo-remoting-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <!-- Minio 对象存储 -->
        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.javen205</groupId>
            <artifactId>IJPay-AliPay</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <!--	开发环境		-->
            <id>dev</id>
            <properties>
                <profileActive>dev</profileActive>
            </properties>
            <!--	默认激活的环境		-->
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <profileActive>prod</profileActive>
            </properties>
        </profile>
        <profile>
            <id>nas</id>
            <properties>
                <profileActive>nas</profileActive>
            </properties>
        </profile>

    </profiles>

        <!-- 构建 -->
        <build>
            <resources>
                <resource>
                    <directory>src/main/resources</directory>
                    <includes>
                        <include>application-${profileActive}.yml</include>
                        <include>application.yml</include>
                        <include>**/*.xml</include>
                    </includes>
                    <filtering>true</filtering>
                </resource>
                <resource>
                    <directory>src/main/java</directory>
                    <includes>
                        <include>**/*.xml</include>
                    </includes>
                </resource>
            </resources>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <configuration>
                        <excludes>
                            <exclude>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                            </exclude>
                        </excludes>
                    </configuration>

                </plugin>
            </plugins>
        </build>


</project>

