# 网关端口
server:
  port: 2786

spring:
  application:
    name: apimix-consumer
  cloud:
    gateway:
      routes:
        - id: backend_router
          uri: http://127.0.0.1:8091
          predicates:
            - Path=/api/**
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  application:
    name: apimix-consumer


logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    org:
      springframework:
        cloud:
          gateway: info

